### PR TITLE
Discuss how to create an API to easily and safely monkey patch Mongo.Collection

### PR DESCRIPTION
**Pull request by Sivli-Embir**
You don't have to merge this! I wanted to ask if you mind if we extract idempotentTransform into its own package (it can be renamed)?

### CODE REVIEW

**Comment by rclai** [comment]
Oh that's a good idea, did you want to create that package and I'll include it as a dependency?

**Comment by Sivli-Embir** [comment]
Its your code so you or me; I don't mind publishing it but you may be better at maintaining it? I could also add it to https://github.com/Meteor-Reaction and add you to a group that maintains it. Your call.

**Comment by rclai** [comment]
Okay I'll write it, just give me until tonight, if not the weekend.

**Comment by Sivli-Embir** [comment]
Thanks! Ping me when its ready and I will use it in [CanDO](https://github.com/Meteor-Reaction/CanDo).

**Comment by Sivli-Embir** [comment]
@rclai checkout https://github.com/Meteor-Reaction/shadow-collection and tell me what you think. Its an alternative to what I proposed in this commit and removes the need to depend on collection helpers. Additionally I will be asking collection helpers if they want to use this too. It lets the transform function be usable again and will not conflict with other packages doing the same thing (unless there is an namespace conflict, last write wins).

**Comment by rclai** [comment]
@Kestanous that looks cool, however, its intent is to modify the `_transform` property, which might be too specific. What about making it the constructor more open-ended so that it allows you to be more flexible with what you want to do with the Mongo.Collection constructor, that way, other packages like collection-hooks, collection2, collection-helpers, your shadow collection can use it:

``` js
wrapMongoConstructor = function (customFunctions) {
  var constructor = Mongo.Collection;

  Mongo.Collection = function() {
    var args = _.toArray(arguments);
    _.isFunction(customFunctions.before) && customFunctions.before.apply(this, args);
    var ret = constructor.apply(this, args);
    _.isFunction(customFunctions.after) && customFunctions.after.apply(this, args);
    return ret;
  };

  Mongo.Collection.prototype = Object.create(constructor.prototype);
  Mongo.Collection.prototype.constructor = Mongo.Collection;

  _.extend(Mongo.Collection, constructor);

  Meteor.Collection = Mongo.Collection;
};
```

I know it looks kind of weird that I did before/after, but I had to do a before function for a specific case where I needed to dynamically modify some of the arguments before it went into the official constructor.

You can then do your shadow stuff

``` js
wrapMongoConstructor({
   before: function () {
       ...
   },
   after: function () {
       if (_.isFunction(this._transform)) {
           transform = _.wrap(this._transform, function () {
            var func = arguments[0], doc = arguments[1]
            doc = runShadows(doc, self)
            return func(doc)
          });
        } else {
             // console.log('transform does not exists')
              transform = function (doc) {
                 return runShadows(doc, self)
               }
         }
     }
})
```

**Comment by Sivli-Embir** [comment]
That sounds great actually. I need to sit down and grok it but I added you to the "shadow" teem on meteor-reaction so feel free to implement as you want. That's a free invitation with no strings, if you don't want to help on that end no hard feelings.

An important aspect of this is the idea of shadow objects for instances, see https://github.com/Meteor-Reaction/shadow-describer. The catch is the shadow object should be usable across packages. I will be using it as I start building models.

Anyway we can take this over there and stop creating noise in your package ^_^

**Comment by rclai** [comment]
Yeah, I can help for sure. So am I actually able to push stuff to the shadow collection repo?

**Pull request closed without merging**
